# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license = 'LGPL' # TODO: check what this license is

[[mods]]
modId = "yourmodid"
version = "${file.jarVersion}"
displayName = "your mod name"
credits = ""
authors = "you"
description = '''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.yourmodid]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.yourmodid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1]"
ordering = "NONE"
side = "BOTH"
