# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license = 'MIT'

[[mods]]
modId = "kotas_discordchat"
version = "${file.jarVersion}"
displayName = "Kota's Discord chat"
credits = "Grimmauld"
authors = "kotakotik22"
description = '''
A server-side mod that links Discord and Minecraft
'''
[[dependencies.kotas_discordchat]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.kotas_discordchat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
